import { useState, type FormEvent } from 'react';
import { ArrowRight, LockKeyhole } from 'lucide-react';
import { api } from '../lib/api';
import type { User } from '../types';
export function AuthForm({onSuccess}:{onSuccess:(user:User)=>void}) {
 const [register,setRegister]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setBusy(true);const data=new FormData(e.currentTarget);try{const result=await api<{user:User}>(`/auth/${register?'register':'login'}`,{method:'POST',body:JSON.stringify({email:data.get('email'),password:data.get('password'),...(register?{name:data.get('name')}:{})})});onSuccess(result.user);}catch(err){setError(err instanceof Error?err.message:'No se pudo iniciar sesión');}finally{setBusy(false);}}
 return <><div className="auth-intro"><span className="feature-icon"><LockKeyhole size={25}/></span><p>{register?'Crea tu espacio personal para seguir tus inversiones.':'Accede a tu cuenta y continúa donde lo dejaste.'}</p></div><form onSubmit={submit} className="form-stack">{register&&<label>Nombre completo<input name="name" required minLength={2} maxLength={80} autoComplete="name" placeholder="Tu nombre"/></label>}<label>Correo electrónico<input name="email" type="email" required autoComplete="email" placeholder="nombre@ejemplo.com" maxLength={254}/></label><label>Contraseña<input name="password" type="password" required minLength={register?12:1} maxLength={128} autoComplete={register?'new-password':'current-password'} placeholder={register?'Al menos 12 caracteres':'Tu contraseña'}/></label>{register&&<p className="muted">Tu cuenta se creará sin fondos. Podrás explorar el panel mientras habilitamos las integraciones.</p>}{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary" disabled={busy}>{busy?'Un momento…':register?'Crear mi cuenta':'Iniciar sesión'}<ArrowRight size={17}/></button></form><button className="auth-switch text-button" onClick={()=>{setRegister(!register);setError('');}}>{register?'Ya tengo una cuenta':'¿Primera vez? Crear una cuenta'}</button></>;
}
