import { useId, useState } from 'react';
import { ArrowUpRight } from 'lucide-react';
import { dateLabel, filterPeriod, type Period } from '../lib/format';
export function PerformanceChart({points}:{points:{date:string;value:number}[]}) {
 const [period,setPeriod] = useState<Period>('3M'); const gradient=useId();
 const data=filterPeriod(points,period); const [hover,setHover]=useState<number|null>(null);
 const min=Math.min(0,...data.map(p=>p.value)); const max=Math.max(5,...data.map(p=>p.value));
 const bottom=Math.floor(min/5)*5, top=Math.ceil(max/5)*5; const range=top-bottom || 5;
 const xy=data.map((p,i)=>({x:45+i/Math.max(1,data.length-1)*655,y:205-(p.value-bottom)/range*180,...p}));
 const line=xy.map((p,i)=>`${i===0?'M':'L'}${p.x},${p.y}`).join(' ');
 const selected=hover===null ? xy[xy.length-1] : xy[hover];
 return <section className="panel performance"><div className="panel-title"><div><h2>Evolución de tu inversión</h2><p>Rendimiento acumulado</p></div><span className="chart-unit">% <ArrowUpRight size={15}/></span></div><div className="chart-toolbar"><div className="chart-legend"><i/> Rendimiento <span>USD</span></div><div className="periods" aria-label="Período del gráfico">{(['1M','3M','6M','1Y','ALL'] as Period[]).map(p=><button key={p} aria-pressed={period===p} className={p===period?'selected':''} onClick={()=>{setPeriod(p);setHover(null);}}>{p==='ALL'?'Todo':p}</button>)}</div></div>{!data.length ? <div className="chart-empty"><p>Tu historia de inversión comienza aquí</p><span>Cuando haya una valoración confirmada, podrás seguir su evolución.</span></div> : <><div className="chart-wrap"><svg viewBox="0 0 730 250" role="img" aria-label={`Rendimiento acumulado. Último valor ${data[data.length-1].value.toFixed(2)} por ciento.`}><defs><linearGradient id={gradient} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#dcb76a" stopOpacity=".28"/><stop offset="100%" stopColor="#dcb76a" stopOpacity="0"/></linearGradient></defs>{Array.from({length:5},(_,i)=>{const y=25+i*45;return <g key={i}><line x1="45" x2="705" y1={y} y2={y} stroke="#292b2f" strokeDasharray="3 5"/><text x="0" y={y+4} fill="#898b92" fontSize="11">{(top-i*range/4).toFixed(0)}%</text></g>;})}<path d={`${line} L${xy[xy.length-1].x},205 L45,205 Z`} fill={`url(#${gradient})`}/><path d={line} fill="none" stroke="#dfba72" strokeWidth="2.5" strokeLinejoin="round" strokeLinecap="round"/>{xy.filter((_,i)=>i===0 || i===xy.length-1 || i%Math.max(1,Math.floor(xy.length/4))===0).map(p=><text key={p.date} x={p.x} y="236" fill="#898b92" fontSize="11" textAnchor={p.x===45?'start':p.x===700?'end':'middle'}>{dateLabel(p.date)}</text>)}{xy.map((p,i)=><rect key={p.date} x={p.x-12} y="20" width="24" height="195" fill="transparent" onMouseEnter={()=>setHover(i)} onMouseLeave={()=>setHover(null)}/>)}{selected && <g pointerEvents="none"><line x1={selected.x} x2={selected.x} y1={selected.y} y2="205" stroke="#d5b36c" opacity=".25" strokeDasharray="3 4"/><circle cx={selected.x} cy={selected.y} r="5" fill="#dfba72" stroke="#171819" strokeWidth="3"/></g>}</svg></div><div className="chart-caption"><span>{selected ? dateLabel(selected.date,true):''}</span><strong>{selected?.value.toFixed(2)}% acumulado</strong></div><details className="chart-data"><summary>Ver datos del gráfico</summary><div className="data-points">{data.map(p=><p key={p.date}>{dateLabel(p.date)} <strong>{p.value.toFixed(2)}%</strong></p>)}</div></details></>}</section>;
}
