import { ArrowDownLeft, ArrowUpRight, TrendingUp, Download, Search } from 'lucide-react';
import { useState } from 'react';
import type { Transaction } from '../types';
import { dateLabel, exportTransactions, formatMoney } from '../lib/format';
export function Transactions({rows,full=false,onMore}:{rows:Transaction[];full?:boolean;onMore?:()=>void}) {
 const [query,setQuery]=useState('');const [type,setType]=useState('all');
 const filtered=rows.filter(t=>t.label.toLowerCase().includes(query.toLowerCase())&&(type==='all'||t.type===type));
 return <section className="panel transactions"><div className="panel-title"><h2>{full?'Historial de movimientos':'Últimos movimientos'}</h2>{full?<button className="button secondary compact" disabled={!filtered.length} onClick={()=>exportTransactions(filtered)}><Download size={16}/> Exportar CSV</button>:<button className="text-button" onClick={onMore}>Ver todos <ArrowUpRight size={15}/></button>}</div>{full&&<div className="table-filters"><label><span>Buscar movimiento</span><div className="search-field"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por concepto"/></div></label><label><span>Tipo de movimiento</span><select value={type} onChange={e=>setType(e.target.value)}><option value="all">Todos los tipos</option><option value="deposit">Depósitos</option><option value="return">Rendimientos</option><option value="withdrawal">Retiros</option></select></label></div>}<div className="table-scroll"><table><thead><tr><th>Movimiento</th><th>Fecha</th><th>Importe</th><th>Estado</th></tr></thead><tbody>{(full?filtered:filtered.slice(0,3)).map(t=><tr key={t.id}><td><div className="movement-name"><span className={`movement-icon ${t.type}`}>{t.type==='deposit'?<ArrowDownLeft size={18}/>:t.type==='return'?<TrendingUp size={18}/>:<ArrowUpRight size={18}/>}</span><div><strong>{t.label}</strong><small>{t.type==='deposit'?'Aporte de capital':t.type==='return'?'Resultado de inversión':'Salida de capital'}</small></div></div></td><td>{dateLabel(t.date)}</td><td className={t.type==='withdrawal'?'':'positive'}>{t.type!=='withdrawal'&& !t.amount.startsWith('-')?'+':''}{formatMoney(t.amount)}</td><td><span className={`status ${t.status}`}><i/>{t.status==='completed'?'Completado':'Pendiente'}</span></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty-state">{query || type!=='all'?'No hay movimientos que coincidan.':'Aún no tienes movimientos. Los aportes confirmados aparecerán aquí.'}</div>}</div></section>;
}
